<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IeuanWalker.GeoUK" Version="1.0.5" />
    <PackageReference Include="IeuanWalker.GeoUK.OSTN" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BodsDotNet\BodsDotNet.csproj" />
  </ItemGroup>

</Project>
