//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf Siri_namespace_mapping.txt -o output --nc siri.xsd
namespace BodsDotNet.Schemas.Siri.Xml
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("lang", Namespace="http://www.w3.org/XML/1998/namespace", AnonymousType=true)]
    public enum Lang
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("AA")]
        Aa,
        
        [System.Xml.Serialization.XmlEnumAttribute("AB")]
        Ab,
        
        [System.Xml.Serialization.XmlEnumAttribute("AF")]
        Af,
        
        [System.Xml.Serialization.XmlEnumAttribute("AM")]
        Am,
        
        [System.Xml.Serialization.XmlEnumAttribute("AR")]
        Ar,
        
        [System.Xml.Serialization.XmlEnumAttribute("AS")]
        As,
        
        [System.Xml.Serialization.XmlEnumAttribute("AY")]
        Ay,
        
        [System.Xml.Serialization.XmlEnumAttribute("AZ")]
        Az,
        
        [System.Xml.Serialization.XmlEnumAttribute("BA")]
        Ba,
        
        [System.Xml.Serialization.XmlEnumAttribute("BE")]
        Be,
        
        [System.Xml.Serialization.XmlEnumAttribute("BG")]
        Bg,
        
        [System.Xml.Serialization.XmlEnumAttribute("BH")]
        Bh,
        
        [System.Xml.Serialization.XmlEnumAttribute("BI")]
        Bi,
        
        [System.Xml.Serialization.XmlEnumAttribute("BN")]
        Bn,
        
        [System.Xml.Serialization.XmlEnumAttribute("BO")]
        Bo,
        
        [System.Xml.Serialization.XmlEnumAttribute("BR")]
        Br,
        
        [System.Xml.Serialization.XmlEnumAttribute("CA")]
        Ca,
        
        [System.Xml.Serialization.XmlEnumAttribute("CO")]
        Co,
        
        [System.Xml.Serialization.XmlEnumAttribute("CS")]
        Cs,
        
        [System.Xml.Serialization.XmlEnumAttribute("CY")]
        Cy,
        
        [System.Xml.Serialization.XmlEnumAttribute("DA")]
        Da,
        
        [System.Xml.Serialization.XmlEnumAttribute("DE")]
        De,
        
        [System.Xml.Serialization.XmlEnumAttribute("DZ")]
        Dz,
        
        [System.Xml.Serialization.XmlEnumAttribute("EL")]
        El,
        
        [System.Xml.Serialization.XmlEnumAttribute("EN")]
        En,
        
        [System.Xml.Serialization.XmlEnumAttribute("EO")]
        Eo,
        
        [System.Xml.Serialization.XmlEnumAttribute("ES")]
        Es,
        
        [System.Xml.Serialization.XmlEnumAttribute("ET")]
        Et,
        
        [System.Xml.Serialization.XmlEnumAttribute("EU")]
        Eu,
        
        [System.Xml.Serialization.XmlEnumAttribute("FA")]
        Fa,
        
        [System.Xml.Serialization.XmlEnumAttribute("FI")]
        Fi,
        
        [System.Xml.Serialization.XmlEnumAttribute("FJ")]
        Fj,
        
        [System.Xml.Serialization.XmlEnumAttribute("FO")]
        Fo,
        
        [System.Xml.Serialization.XmlEnumAttribute("FR")]
        Fr,
        
        [System.Xml.Serialization.XmlEnumAttribute("FY")]
        Fy,
        
        [System.Xml.Serialization.XmlEnumAttribute("GA")]
        Ga,
        
        [System.Xml.Serialization.XmlEnumAttribute("GD")]
        Gd,
        
        [System.Xml.Serialization.XmlEnumAttribute("GL")]
        Gl,
        
        [System.Xml.Serialization.XmlEnumAttribute("GN")]
        Gn,
        
        [System.Xml.Serialization.XmlEnumAttribute("GU")]
        Gu,
        
        [System.Xml.Serialization.XmlEnumAttribute("HA")]
        Ha,
        
        [System.Xml.Serialization.XmlEnumAttribute("HI")]
        Hi,
        
        [System.Xml.Serialization.XmlEnumAttribute("HR")]
        Hr,
        
        [System.Xml.Serialization.XmlEnumAttribute("HU")]
        Hu,
        
        [System.Xml.Serialization.XmlEnumAttribute("HY")]
        Hy,
        
        [System.Xml.Serialization.XmlEnumAttribute("IA")]
        Ia,
        
        [System.Xml.Serialization.XmlEnumAttribute("IE")]
        Ie,
        
        [System.Xml.Serialization.XmlEnumAttribute("IK")]
        Ik,
        
        [System.Xml.Serialization.XmlEnumAttribute("IN")]
        In,
        
        [System.Xml.Serialization.XmlEnumAttribute("IS")]
        Is,
        
        [System.Xml.Serialization.XmlEnumAttribute("IT")]
        It,
        
        [System.Xml.Serialization.XmlEnumAttribute("IW")]
        Iw,
        
        [System.Xml.Serialization.XmlEnumAttribute("JA")]
        Ja,
        
        [System.Xml.Serialization.XmlEnumAttribute("JI")]
        Ji,
        
        [System.Xml.Serialization.XmlEnumAttribute("JW")]
        Jw,
        
        [System.Xml.Serialization.XmlEnumAttribute("KA")]
        Ka,
        
        [System.Xml.Serialization.XmlEnumAttribute("KK")]
        Kk,
        
        [System.Xml.Serialization.XmlEnumAttribute("KL")]
        Kl,
        
        [System.Xml.Serialization.XmlEnumAttribute("KM")]
        Km,
        
        [System.Xml.Serialization.XmlEnumAttribute("KN")]
        Kn,
        
        [System.Xml.Serialization.XmlEnumAttribute("KO")]
        Ko,
        
        [System.Xml.Serialization.XmlEnumAttribute("KS")]
        Ks,
        
        [System.Xml.Serialization.XmlEnumAttribute("KU")]
        Ku,
        
        [System.Xml.Serialization.XmlEnumAttribute("KY")]
        Ky,
        
        [System.Xml.Serialization.XmlEnumAttribute("LA")]
        La,
        
        [System.Xml.Serialization.XmlEnumAttribute("LN")]
        Ln,
        
        [System.Xml.Serialization.XmlEnumAttribute("LO")]
        Lo,
        
        [System.Xml.Serialization.XmlEnumAttribute("LT")]
        Lt,
        
        [System.Xml.Serialization.XmlEnumAttribute("LV")]
        Lv,
        
        [System.Xml.Serialization.XmlEnumAttribute("MG")]
        Mg,
        
        [System.Xml.Serialization.XmlEnumAttribute("MI")]
        Mi,
        
        [System.Xml.Serialization.XmlEnumAttribute("MK")]
        Mk,
        
        [System.Xml.Serialization.XmlEnumAttribute("ML")]
        Ml,
        
        [System.Xml.Serialization.XmlEnumAttribute("MN")]
        Mn,
        
        [System.Xml.Serialization.XmlEnumAttribute("MO")]
        Mo,
        
        [System.Xml.Serialization.XmlEnumAttribute("MR")]
        Mr,
        
        [System.Xml.Serialization.XmlEnumAttribute("MS")]
        Ms,
        
        [System.Xml.Serialization.XmlEnumAttribute("MT")]
        Mt,
        
        [System.Xml.Serialization.XmlEnumAttribute("MY")]
        My,
        
        [System.Xml.Serialization.XmlEnumAttribute("NA")]
        Na,
        
        [System.Xml.Serialization.XmlEnumAttribute("NE")]
        Ne,
        
        [System.Xml.Serialization.XmlEnumAttribute("NL")]
        Nl,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
        
        [System.Xml.Serialization.XmlEnumAttribute("OC")]
        Oc,
        
        [System.Xml.Serialization.XmlEnumAttribute("OM")]
        Om,
        
        [System.Xml.Serialization.XmlEnumAttribute("OR")]
        Or,
        
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        Pa,
        
        [System.Xml.Serialization.XmlEnumAttribute("PL")]
        Pl,
        
        [System.Xml.Serialization.XmlEnumAttribute("PS")]
        Ps,
        
        [System.Xml.Serialization.XmlEnumAttribute("PT")]
        Pt,
        
        [System.Xml.Serialization.XmlEnumAttribute("QU")]
        Qu,
        
        [System.Xml.Serialization.XmlEnumAttribute("RM")]
        Rm,
        
        [System.Xml.Serialization.XmlEnumAttribute("RN")]
        Rn,
        
        [System.Xml.Serialization.XmlEnumAttribute("RO")]
        Ro,
        
        [System.Xml.Serialization.XmlEnumAttribute("RU")]
        Ru,
        
        [System.Xml.Serialization.XmlEnumAttribute("RW")]
        Rw,
        
        [System.Xml.Serialization.XmlEnumAttribute("SA")]
        Sa,
        
        [System.Xml.Serialization.XmlEnumAttribute("SD")]
        Sd,
        
        [System.Xml.Serialization.XmlEnumAttribute("SG")]
        Sg,
        
        [System.Xml.Serialization.XmlEnumAttribute("SH")]
        Sh,
        
        [System.Xml.Serialization.XmlEnumAttribute("SI")]
        Si,
        
        [System.Xml.Serialization.XmlEnumAttribute("SK")]
        Sk,
        
        [System.Xml.Serialization.XmlEnumAttribute("SL")]
        Sl,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM")]
        Sm,
        
        [System.Xml.Serialization.XmlEnumAttribute("SN")]
        Sn,
        
        [System.Xml.Serialization.XmlEnumAttribute("SO")]
        So,
        
        [System.Xml.Serialization.XmlEnumAttribute("SQ")]
        Sq,
        
        [System.Xml.Serialization.XmlEnumAttribute("SR")]
        Sr,
        
        [System.Xml.Serialization.XmlEnumAttribute("SS")]
        Ss,
        
        [System.Xml.Serialization.XmlEnumAttribute("ST")]
        St,
        
        [System.Xml.Serialization.XmlEnumAttribute("SU")]
        Su,
        
        [System.Xml.Serialization.XmlEnumAttribute("SV")]
        Sv,
        
        [System.Xml.Serialization.XmlEnumAttribute("SW")]
        Sw,
        
        [System.Xml.Serialization.XmlEnumAttribute("TA")]
        Ta,
        
        [System.Xml.Serialization.XmlEnumAttribute("TE")]
        Te,
        
        [System.Xml.Serialization.XmlEnumAttribute("TG")]
        Tg,
        
        [System.Xml.Serialization.XmlEnumAttribute("TH")]
        Th,
        
        [System.Xml.Serialization.XmlEnumAttribute("TI")]
        Ti,
        
        [System.Xml.Serialization.XmlEnumAttribute("TK")]
        Tk,
        
        [System.Xml.Serialization.XmlEnumAttribute("TL")]
        Tl,
        
        [System.Xml.Serialization.XmlEnumAttribute("TN")]
        Tn,
        
        [System.Xml.Serialization.XmlEnumAttribute("TO")]
        To,
        
        [System.Xml.Serialization.XmlEnumAttribute("TR")]
        Tr,
        
        [System.Xml.Serialization.XmlEnumAttribute("TS")]
        Ts,
        
        [System.Xml.Serialization.XmlEnumAttribute("TT")]
        Tt,
        
        [System.Xml.Serialization.XmlEnumAttribute("TW")]
        Tw,
        
        [System.Xml.Serialization.XmlEnumAttribute("UK")]
        Uk,
        
        [System.Xml.Serialization.XmlEnumAttribute("UR")]
        Ur,
        
        [System.Xml.Serialization.XmlEnumAttribute("UZ")]
        Uz,
        
        [System.Xml.Serialization.XmlEnumAttribute("VI")]
        Vi,
        
        [System.Xml.Serialization.XmlEnumAttribute("VO")]
        Vo,
        
        [System.Xml.Serialization.XmlEnumAttribute("WO")]
        Wo,
        
        [System.Xml.Serialization.XmlEnumAttribute("XH")]
        Xh,
        
        [System.Xml.Serialization.XmlEnumAttribute("YO")]
        Yo,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZH")]
        Zh,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZU")]
        Zu,
    }
}
