//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf Siri_namespace_mapping.txt -o output --nc siri.xsd
namespace BodsDotNet.Schemas.Siri.Ifopt.Acsb
{
    
    
    /// <summary>
    /// <para>Enumeration of values for an accessibility value.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Enumeration of values for an accessibility value.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum AccessibilityEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("unknown")]
        Unknown,
        
        [System.Xml.Serialization.XmlEnumAttribute("false")]
        False,
        
        [System.Xml.Serialization.XmlEnumAttribute("true")]
        True,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AudibleSignalsAvailable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EscalatorFreeAccess))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GuideDogAccess))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LiftFreeAccess))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StepFreeAccess))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VisualSignsAvailable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WheelchairAccess))]
    public partial class AccessibilityStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public AccessibilityEnumeration Value { get; set; }
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT has step free access.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has step free access.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("StepFreeAccess", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class StepFreeAccess : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Type for accessibility.</para>
    /// <para>Whether a PLACE / SITE ELEMENT is wheelchair accessible.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for accessibility. Whether a PLACE / SITE ELEMENT is wheelchair accessible.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("WheelchairAccess", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class WheelchairAccess : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT has escalator free access.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has escalator free access.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("EscalatorFreeAccess", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class EscalatorFreeAccess : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT has lift free access.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has lift free access.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LiftFreeAccess", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class LiftFreeAccess : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT is wheelchair accessible.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT is wheelchair accessible.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AudibleSignalsAvailable", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class AudibleSignalsAvailable : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT has Visual signals availble for the free access.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has Visual signals availble for the free access.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("VisualSignsAvailable", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class VisualSignsAvailable : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Whether a PLACE / SITE ELEMENT allows guide dog access.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT allows guide dog access.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("GuideDogAccess", Namespace="http://www.ifopt.org.uk/acsb")]
    public partial class GuideDogAccess : AccessibilityStructure
    {
    }
    
    /// <summary>
    /// <para>Group of mobility LIMITATIONs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Group of mobility LIMITATIONs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    public partial interface IMobilityLimitationGroup
    {
        
        AccessibilityStructure WheelchairAccess
        {
            get;
            set;
        }
        
        AccessibilityStructure StepFreeAccess
        {
            get;
            set;
        }
        
        AccessibilityStructure EscalatorFreeAccess
        {
            get;
            set;
        }
        
        AccessibilityStructure LiftFreeAccess
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Group of sensory LIMITATIONs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Group of sensory LIMITATIONs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    public partial interface ISensoryLimitationGroup
    {
        
        /// <summary>
        /// <para>Whether a PLACE / SITE ELEMENT has Audible signals for the viusally impaired.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has Audible signals for the viusally impaired.")]
        AccessibilityStructure AudibleSignalsAvailable
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Whether a PLACE / SITE ELEMENT has Visual signals for the hearing impaired.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has Visual signals for the hearing impaired.")]
        AccessibilityStructure VisualSignsAvailable
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Type for accessibility needs. Records the requirementrs of a passenger that may affect choice of facilities.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for accessibility needs. Records the requirementrs of a passenger that may a" +
        "ffect choice of facilities.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PassengerAccessibilityNeedsStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PassengerAccessibilityNeedsStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UserNeedStructure> _userNeed;
        
        /// <summary>
        /// <para>Specific pyschosensory need that may constrain choice of services and facilities.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Specific pyschosensory need that may constrain choice of services and facilities." +
            "")]
        [System.Xml.Serialization.XmlElementAttribute("UserNeed")]
        public System.Collections.ObjectModel.Collection<UserNeedStructure> UserNeed
        {
            get
            {
                return _userNeed;
            }
            private set
            {
                _userNeed = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the UserNeed collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserNeedSpecified
        {
            get
            {
                return (this.UserNeed.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PassengerAccessibilityNeedsStructure" /> class.</para>
        /// </summary>
        public PassengerAccessibilityNeedsStructure()
        {
            this._userNeed = new System.Collections.ObjectModel.Collection<UserNeedStructure>();
        }
        
        /// <summary>
        /// <para>Whether the passenger is accompanied by a carer or assistant.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether the passenger is accompanied by a carer or assistant.")]
        [System.Xml.Serialization.XmlElementAttribute("AccompaniedByCarer")]
        public bool AccompaniedByCarer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AccompaniedByCarer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccompaniedByCarerSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Type for of a specific need.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for of a specific need.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UserNeedStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserNeedStructure : IUserNeedGroup
    {
        
        /// <summary>
        /// <para>Passenger mobility USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger mobility USER NEED for which SUITABILITY is specified.")]
        [System.Xml.Serialization.XmlElementAttribute("MobilityNeed")]
        public MobilityEnumeration MobilityNeed { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MobilityNeed property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MobilityNeedSpecified { get; set; }
        
        /// <summary>
        /// <para>Passenger mobility USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger mobility USER NEED for which SUITABILITY is specified.")]
        [System.Xml.Serialization.XmlElementAttribute("PsychosensoryNeed")]
        public PyschosensoryNeedEnumeration PsychosensoryNeed { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PsychosensoryNeed property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PsychosensoryNeedSpecified { get; set; }
        
        /// <summary>
        /// <para>Passenger medical USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger medical USER NEED for which SUITABILITY is specified.")]
        [System.Xml.Serialization.XmlElementAttribute("MedicalNeed")]
        public UserNeedGroupMedicalNeed MedicalNeed { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MedicalNeed property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicalNeedSpecified { get; set; }
        
        /// <summary>
        /// <para>Passenger enceumbrance USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger enceumbrance USER NEED for which SUITABILITY is specified.")]
        [System.Xml.Serialization.XmlElementAttribute("EncumbranceNeed")]
        public EncumbranceEnumeration EncumbranceNeed { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EncumbranceNeed property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EncumbranceNeedSpecified { get; set; }
        
        /// <summary>
        /// <para>Whether USER NEED is included or excluded. Default is 'included'.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether USER NEED is included or excluded. Default is \'included\'.")]
        [System.Xml.Serialization.XmlElementAttribute("Excluded")]
        public bool Excluded { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Excluded property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExcludedSpecified { get; set; }
        
        /// <summary>
        /// <para>Relative ranking of USER NEED on a sclae 1-5</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Relative ranking of USER NEED on a sclae 1-5")]
        [System.Xml.Serialization.XmlElementAttribute("NeedRanking")]
        public string NeedRanking { get; set; }
        
        /// <summary>
        /// <para>Extensions to USETR NEED.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Extensions to USETR NEED.")]
        [System.Xml.Serialization.XmlElementAttribute("Extensions")]
        public object Extensions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    public partial interface IUserNeedGroup
    {
        
        /// <summary>
        /// <para>Passenger mobility USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger mobility USER NEED for which SUITABILITY is specified.")]
        MobilityEnumeration MobilityNeed
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Passenger mobility USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger mobility USER NEED for which SUITABILITY is specified.")]
        PyschosensoryNeedEnumeration PsychosensoryNeed
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Passenger medical USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger medical USER NEED for which SUITABILITY is specified.")]
        UserNeedGroupMedicalNeed MedicalNeed
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Passenger enceumbrance USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Passenger enceumbrance USER NEED for which SUITABILITY is specified.")]
        EncumbranceEnumeration EncumbranceNeed
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Identification of mobility USER NEEDs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Identification of mobility USER NEEDs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MobilityEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum MobilityEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("wheelchair")]
        Wheelchair,
        
        [System.Xml.Serialization.XmlEnumAttribute("assistedWheelchair")]
        AssistedWheelchair,
        
        [System.Xml.Serialization.XmlEnumAttribute("motorizedWheelchair")]
        MotorizedWheelchair,
        
        [System.Xml.Serialization.XmlEnumAttribute("walkingFrame")]
        WalkingFrame,
        
        [System.Xml.Serialization.XmlEnumAttribute("restrictedMobility")]
        RestrictedMobility,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherMobilityNeed")]
        OtherMobilityNeed,
    }
    
    /// <summary>
    /// <para>Enumeration of specific psychosensory USER NEEDs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Enumeration of specific psychosensory USER NEEDs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PyschosensoryNeedEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum PyschosensoryNeedEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("visualImpairment")]
        VisualImpairment,
        
        [System.Xml.Serialization.XmlEnumAttribute("auditoryImpairment")]
        AuditoryImpairment,
        
        [System.Xml.Serialization.XmlEnumAttribute("cognitiveInputImpairment")]
        CognitiveInputImpairment,
        
        [System.Xml.Serialization.XmlEnumAttribute("averseToLifts")]
        AverseToLifts,
        
        [System.Xml.Serialization.XmlEnumAttribute("averseToEscalators")]
        AverseToEscalators,
        
        [System.Xml.Serialization.XmlEnumAttribute("averseToConfinedSpaces")]
        AverseToConfinedSpaces,
        
        [System.Xml.Serialization.XmlEnumAttribute("averseToCrowds")]
        AverseToCrowds,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherPsychosensoryNeed")]
        OtherPsychosensoryNeed,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UserNeedGroupMedicalNeed", Namespace="http://www.ifopt.org.uk/acsb", AnonymousType=true)]
    public enum UserNeedGroupMedicalNeed
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("allergic")]
        Allergic,
        
        [System.Xml.Serialization.XmlEnumAttribute("heartCondition")]
        HeartCondition,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherMedicalNeed")]
        OtherMedicalNeed,
    }
    
    /// <summary>
    /// <para>Enumeration of specific encumbrances USER NEEDs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Enumeration of specific encumbrances USER NEEDs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EncumbranceEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum EncumbranceEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("luggageEncumbered")]
        LuggageEncumbered,
        
        [System.Xml.Serialization.XmlEnumAttribute("pushchair")]
        Pushchair,
        
        [System.Xml.Serialization.XmlEnumAttribute("baggageTrolley")]
        BaggageTrolley,
        
        [System.Xml.Serialization.XmlEnumAttribute("oversizeBaggage")]
        OversizeBaggage,
        
        [System.Xml.Serialization.XmlEnumAttribute("guideDog")]
        GuideDog,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherAnimal")]
        OtherAnimal,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherEncumbrance")]
        OtherEncumbrance,
    }
    
    /// <summary>
    /// <para>Enumeration of specific Medical USER NEEDs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Enumeration of specific Medical USER NEEDs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MedicalNeedEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum MedicalNeedEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("allergic")]
        Allergic,
        
        [System.Xml.Serialization.XmlEnumAttribute("heartCondition")]
        HeartCondition,
        
        [System.Xml.Serialization.XmlEnumAttribute("otherMedicalNeed")]
        OtherMedicalNeed,
    }
    
    /// <summary>
    /// <para>Type for of a specific SUITABILITY.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for of a specific SUITABILITY.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SuitabilityStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuitabilityStructure
    {
        
        /// <summary>
        /// <para>Whether the Facility is suitable.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether the Facility is suitable.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Suitable")]
        public SuitabilityEnumeration Suitable { get; set; }
        
        /// <summary>
        /// <para>USER NEED for which SUITABILITY is specified.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("USER NEED for which SUITABILITY is specified.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("UserNeed")]
        public UserNeedStructure UserNeed { get; set; }
    }
    
    /// <summary>
    /// <para>Identification of specific SUITABILITY.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Identification of specific SUITABILITY.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SuitabilityEnumeration", Namespace="http://www.ifopt.org.uk/acsb")]
    public enum SuitabilityEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("suitable")]
        Suitable,
        
        [System.Xml.Serialization.XmlEnumAttribute("notSuitable")]
        NotSuitable,
    }
    
    /// <summary>
    /// <para>Type for reference to an identifier of a hazard within a stop place.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for reference to an identifier of a hazard within a stop place.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LimitationRefStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LimitationRefStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }
    
    /// <summary>
    /// <para>Type for limitation on navigation.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for limitation on navigation.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityLimitationStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccessibilityLimitationStructure : BodsDotNet.Schemas.Siri.Ifopt.Acsb.IMobilityLimitationGroup, BodsDotNet.Schemas.Siri.Ifopt.Acsb.ISensoryLimitationGroup
    {
        
        /// <summary>
        /// <para>Identifier of LIMITATION.</para>
        /// <para>Type for identifier of a hazard within a stop place.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identifier of LIMITATION.")]
        [System.Xml.Serialization.XmlElementAttribute("LimitationId")]
        public string LimitationId { get; set; }
        
        /// <summary>
        /// <para>Validty condition governing applicability of LIMITATION.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Validty condition governing applicability of LIMITATION.")]
        [System.Xml.Serialization.XmlElementAttribute("ValidityCondition")]
        public BodsDotNet.Schemas.Siri.Ifopt.ValidityConditionStructure ValidityCondition { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("WheelchairAccess")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure WheelchairAccess { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StepFreeAccess")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure StepFreeAccess { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EscalatorFreeAccess")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure EscalatorFreeAccess { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LiftFreeAccess")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure LiftFreeAccess { get; set; }
        
        /// <summary>
        /// <para>Whether a PLACE / SITE ELEMENT has Audible signals for the viusally impaired.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has Audible signals for the viusally impaired.")]
        [System.Xml.Serialization.XmlElementAttribute("AudibleSignalsAvailable")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure AudibleSignalsAvailable { get; set; }
        
        /// <summary>
        /// <para>Whether a PLACE / SITE ELEMENT has Visual signals for the hearing impaired.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Whether a PLACE / SITE ELEMENT has Visual signals for the hearing impaired.")]
        [System.Xml.Serialization.XmlElementAttribute("VisualSignsAvailable")]
        public BodsDotNet.Schemas.Siri.Ifopt.Acsb.AccessibilityStructure VisualSignsAvailable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Extensions", Namespace="http://www.ifopt.org.uk/ifopt")]
        public BodsDotNet.Schemas.Siri.Ifopt.Extensions Extensions { get; set; }
    }
    
    /// <summary>
    /// <para>Type for Assesment.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for Assesment.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityAssessmentStructure", Namespace="http://www.ifopt.org.uk/acsb")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccessibilityAssessmentStructure
    {
        
        /// <summary>
        /// <para>Summary indication as to whether the component is considered to be accessible or not.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Summary indication as to whether the component is considered to be accessible or " +
            "not.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MobilityImpairedAccess")]
        public bool MobilityImpairedAccess { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure> _limitations;
        
        /// <summary>
        /// <para>The Limitations that apply to component.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The Limitations that apply to component.")]
        [System.Xml.Serialization.XmlArrayAttribute("Limitations")]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccessibilityLimitation", Namespace="http://www.ifopt.org.uk/acsb")]
        public System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure> Limitations
        {
            get
            {
                return _limitations;
            }
            private set
            {
                _limitations = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Limitations collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimitationsSpecified
        {
            get
            {
                return (this.Limitations.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AccessibilityAssessmentStructure" /> class.</para>
        /// </summary>
        public AccessibilityAssessmentStructure()
        {
            this._limitations = new System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure>();
            this._suitabilities = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure> _suitabilities;
        
        /// <summary>
        /// <para>The Suitability of the component to meet specifc user needs.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The Suitability of the component to meet specifc user needs.")]
        [System.Xml.Serialization.XmlArrayAttribute("Suitabilities")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Suitability", Namespace="http://www.ifopt.org.uk/acsb")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure> Suitabilities
        {
            get
            {
                return _suitabilities;
            }
            private set
            {
                _suitabilities = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Suitabilities collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuitabilitiesSpecified
        {
            get
            {
                return (this.Suitabilities.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Extensions", Namespace="http://www.ifopt.org.uk/ifopt")]
        public BodsDotNet.Schemas.Siri.Ifopt.Extensions Extensions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityAssessmentStructureLimitations", Namespace="http://www.ifopt.org.uk/acsb", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccessibilityAssessmentStructureLimitations
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure> _accessibilityLimitation;
        
        /// <summary>
        /// <para>The accessibility limitations of a component.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The accessibility limitations of a component.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AccessibilityLimitation")]
        public System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure> AccessibilityLimitation
        {
            get
            {
                return _accessibilityLimitation;
            }
            private set
            {
                _accessibilityLimitation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AccessibilityAssessmentStructureLimitations" /> class.</para>
        /// </summary>
        public AccessibilityAssessmentStructureLimitations()
        {
            this._accessibilityLimitation = new System.Collections.ObjectModel.Collection<AccessibilityLimitationStructure>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccessibilityAssessmentStructureSuitabilities", Namespace="http://www.ifopt.org.uk/acsb", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccessibilityAssessmentStructureSuitabilities
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure> _suitability;
        
        /// <summary>
        /// <para>The Suitability of com[onent to meet a specifc user need.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The Suitability of com[onent to meet a specifc user need.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Suitability")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure> Suitability
        {
            get
            {
                return _suitability;
            }
            private set
            {
                _suitability = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AccessibilityAssessmentStructureSuitabilities" /> class.</para>
        /// </summary>
        public AccessibilityAssessmentStructureSuitabilities()
        {
            this._suitability = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.Siri.Ifopt.Acsb.SuitabilityStructure>();
        }
    }
}
