<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IeuanWalker.GeoUK" Version="1.0.5" />
    <PackageReference Include="IeuanWalker.GeoUK.OSTN" Version="1.0.5" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BodsDotNet\BodsDotNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lib\leaflet\" />
    <Folder Include="wwwroot\lib\leaflet-polylineoffset\" />
  </ItemGroup>

</Project>
