//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf TransXChange_namespace_mapping.txt -o output --nc TransXChange_general.xsd
namespace BodsDotNet.Schemas.TransXChange.People.Bs7666
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BSaddressStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BS7666Address", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BSaddressStructure
    {
        
        /// <summary>
        /// <para>Secondary Addressable Object</para>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Pattern: [0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Secondary Addressable Object")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?")]
        [System.Xml.Serialization.XmlElementAttribute("SAON")]
        public string Saon { get; set; }
        
        /// <summary>
        /// <para>Primary Addressable Object</para>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Pattern: [0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Primary Addressable Object")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PAON")]
        public string Paon { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetDescription")]
        public string StreetDescription { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(uint), "1", "99999999", ConvertValueInInvariantCulture=true)]
        [System.Xml.Serialization.XmlElementAttribute("UniqueStreetReferenceNumber")]
        public uint UniqueStreetReferenceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UniqueStreetReferenceNumber property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UniqueStreetReferenceNumberSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(35)]
        [System.Xml.Serialization.XmlElementAttribute("Locality")]
        public string Locality { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _town;
        
        [System.Xml.Serialization.XmlElementAttribute("Town")]
        public System.Collections.ObjectModel.Collection<string> Town
        {
            get
            {
                return _town;
            }
            private set
            {
                _town = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Town collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TownSpecified
        {
            get
            {
                return (this.Town.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BSaddressStructure" /> class.</para>
        /// </summary>
        public BSaddressStructure()
        {
            this._town = new System.Collections.ObjectModel.Collection<string>();
            this._administrativeArea = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _administrativeArea;
        
        [System.Xml.Serialization.XmlElementAttribute("AdministrativeArea")]
        public System.Collections.ObjectModel.Collection<string> AdministrativeArea
        {
            get
            {
                return _administrativeArea;
            }
            private set
            {
                _administrativeArea = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AdministrativeArea collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdministrativeAreaSpecified
        {
            get
            {
                return (this.AdministrativeArea.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("PostTown")]
        public string PostTown { get; set; }
        
        /// <summary>
        /// <para>complex pattern for postcode, which matches definition, accepted by some parsers is: "(GIR 0AA)|((([A-Z-[QVX]][0-9][0-9]?)|(([A-Z-[QVX]][A-Z-[IJZ]][0-9][0-9]?)|(([A-Z-[QVX]][0-9][A-HJKSTUW])|([A-Z-[QVX]][A-Z-[IJZ]][0-9][ABEHMNPRVWXY])))) [0-9][A-Z-[CIKMOV]]{2})"</para>
        /// <para xml:lang="en">Pattern: [A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("PostCode")]
        public string PostCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "1", "999999999999", ConvertValueInInvariantCulture=true)]
        [System.Xml.Serialization.XmlElementAttribute("UniquePropertyReferenceNumber")]
        public ulong UniquePropertyReferenceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UniquePropertyReferenceNumber property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UniquePropertyReferenceNumberSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StreetReferenceTypeType", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum StreetReferenceTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StreetStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StreetStructure
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetReferenceType")]
        public StreetReferenceTypeType StreetReferenceType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StartCoordinate")]
        public CoordinateStructure StartCoordinate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EndCoordinate")]
        public CoordinateStructure EndCoordinate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Tolerance")]
        public decimal Tolerance { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "1", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetVersionNumber")]
        public ushort StreetVersionNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetEntryDate", DataType="date")]
        public System.DateTime StreetEntryDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetClosureDate", DataType="date")]
        public System.DateTime StreetClosureDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "1", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ResponsibleAuthority")]
        public ushort ResponsibleAuthority { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DescriptiveIdentifier")]
        public StreetDescriptiveIdentifierStructure DescriptiveIdentifier { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StreetAlias")]
        public StreetDescriptiveIdentifierStructure StreetAlias { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StreetCrossReferences")]
        public StreetStructureStreetCrossReferences StreetCrossReferences { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(uint), "1", "99999999", ConvertValueInInvariantCulture=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("usrn")]
        public uint Usrn { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Usrn property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsrnSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Coordinate Point based on UK National Grid</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Coordinate Point based on UK National Grid")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoordinateStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoordinateStructure
    {
        
        /// <summary>
        /// <para>Easting Field</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999999.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Easting Field")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "0", "9999999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("X")]
        public ulong X { get; set; }
        
        /// <summary>
        /// <para>Northing Field</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999999.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Northing Field")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "0", "9999999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Y")]
        public ulong Y { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StreetDescriptiveIdentifierStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StreetDescriptiveIdentifierStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StreetDescription")]
        public string StreetDescription { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(35)]
        [System.Xml.Serialization.XmlElementAttribute("Locality")]
        public string Locality { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _town;
        
        [System.Xml.Serialization.XmlElementAttribute("Town")]
        public System.Collections.ObjectModel.Collection<string> Town
        {
            get
            {
                return _town;
            }
            private set
            {
                _town = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Town collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TownSpecified
        {
            get
            {
                return (this.Town.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StreetDescriptiveIdentifierStructure" /> class.</para>
        /// </summary>
        public StreetDescriptiveIdentifierStructure()
        {
            this._town = new System.Collections.ObjectModel.Collection<string>();
            this._administrativeArea = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _administrativeArea;
        
        [System.Xml.Serialization.XmlElementAttribute("AdministrativeArea")]
        public System.Collections.ObjectModel.Collection<string> AdministrativeArea
        {
            get
            {
                return _administrativeArea;
            }
            private set
            {
                _administrativeArea = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AdministrativeArea collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdministrativeAreaSpecified
        {
            get
            {
                return (this.AdministrativeArea.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StreetStructureStreetCrossReferences", Namespace="http://www.govtalk.gov.uk/people/bs7666", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StreetStructureStreetCrossReferences
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _uniqueStreetReferenceNumbers;
        
        [System.Xml.Serialization.XmlElementAttribute("UNIQUE_STREET_REFERENCE_NUMBERS")]
        public System.Collections.ObjectModel.Collection<string> UniqueStreetReferenceNumbers
        {
            get
            {
                return _uniqueStreetReferenceNumbers;
            }
            private set
            {
                _uniqueStreetReferenceNumbers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the UniqueStreetReferenceNumbers collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UniqueStreetReferenceNumbersSpecified
        {
            get
            {
                return (this.UniqueStreetReferenceNumbers.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StreetStructureStreetCrossReferences" /> class.</para>
        /// </summary>
        public StreetStructureStreetCrossReferences()
        {
            this._uniqueStreetReferenceNumbers = new System.Collections.ObjectModel.Collection<string>();
            this._elementaryStreetUnit = new System.Collections.ObjectModel.Collection<ElementaryStreetUnitStructure>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ElementaryStreetUnitStructure> _elementaryStreetUnit;
        
        [System.Xml.Serialization.XmlElementAttribute("ElementaryStreetUnit")]
        public System.Collections.ObjectModel.Collection<ElementaryStreetUnitStructure> ElementaryStreetUnit
        {
            get
            {
                return _elementaryStreetUnit;
            }
            private set
            {
                _elementaryStreetUnit = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElementaryStreetUnit collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElementaryStreetUnitSpecified
        {
            get
            {
                return (this.ElementaryStreetUnit.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElementaryStreetUnitStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElementaryStreetUnitStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ESUidentity")]
        public string EsUidentity { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "1", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ESUversion")]
        public ushort EsUversion { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ESUentryDate", DataType="date")]
        public System.DateTime EsUentryDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ESUclosureDate", DataType="date")]
        public System.DateTime EsUclosureDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EsUclosureDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EsUclosureDateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StartCoordinate")]
        public CoordinateStructure StartCoordinate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EndCoordinate")]
        public CoordinateStructure EndCoordinate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Tolerance")]
        public decimal Tolerance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoordinateStructure> _intermediateCoord;
        
        [System.Xml.Serialization.XmlElementAttribute("IntermediateCoord")]
        public System.Collections.ObjectModel.Collection<CoordinateStructure> IntermediateCoord
        {
            get
            {
                return _intermediateCoord;
            }
            private set
            {
                _intermediateCoord = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IntermediateCoord collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntermediateCoordSpecified
        {
            get
            {
                return (this.IntermediateCoord.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElementaryStreetUnitStructure" /> class.</para>
        /// </summary>
        public ElementaryStreetUnitStructure()
        {
            this._intermediateCoord = new System.Collections.ObjectModel.Collection<CoordinateStructure>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BLPUpolygonStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BlpUpolygonStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(byte), "1", "99", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PolygonID")]
        public byte PolygonId { get; set; }
        
        /// <summary>
        /// <para>H to represent a hole or not present</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("H to represent a hole or not present")]
        [System.Xml.Serialization.XmlElementAttribute("PolygonType")]
        public BlpUpolygonStructurePolygonType PolygonType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PolygonType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonTypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoordinateStructure> _vertices;
        
        [System.Xml.Serialization.XmlElementAttribute("Vertices")]
        public System.Collections.ObjectModel.Collection<CoordinateStructure> Vertices
        {
            get
            {
                return _vertices;
            }
            private set
            {
                _vertices = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Vertices collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerticesSpecified
        {
            get
            {
                return (this.Vertices.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BlpUpolygonStructure" /> class.</para>
        /// </summary>
        public BlpUpolygonStructure()
        {
            this._vertices = new System.Collections.ObjectModel.Collection<CoordinateStructure>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExternalRef")]
        public ulong ExternalRef { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExternalRef property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExternalRefSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BlpUpolygonStructurePolygonType", Namespace="http://www.govtalk.gov.uk/people/bs7666", AnonymousType=true)]
    public enum BlpUpolygonStructurePolygonType
    {
        
        H,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BLPUextentStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BlpUextentStructure
    {
        
        /// <summary>
        /// <para>Description of Source of BLPU Extent</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Description of Source of BLPU Extent")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SourceDescription")]
        public string SourceDescription { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtentEntryDate", DataType="date")]
        public System.DateTime ExtentEntryDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtentSourceDate", DataType="date")]
        public System.DateTime ExtentSourceDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtentStartDate", DataType="date")]
        public System.DateTime ExtentStartDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExtentEndDate", DataType="date")]
        public System.DateTime ExtentEndDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExtentEndDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtentEndDateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtentLastUpdateDate", DataType="date")]
        public System.DateTime ExtentLastUpdateDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BlpUpolygonStructure> _extentDefinition;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtentDefinition")]
        public System.Collections.ObjectModel.Collection<BlpUpolygonStructure> ExtentDefinition
        {
            get
            {
                return _extentDefinition;
            }
            private set
            {
                _extentDefinition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BlpUextentStructure" /> class.</para>
        /// </summary>
        public BlpUextentStructure()
        {
            this._extentDefinition = new System.Collections.ObjectModel.Collection<BlpUpolygonStructure>();
        }
    }
    
    /// <summary>
    /// <para>Provenance Code values
    ///
    ///					T = Registered land title
    ///
    ///					L = Unregistered land title
    ///
    ///					F = Formal tenancy agreement
    ///
    ///					R = Rental agreement
    ///
    ///					P = Physical features
    ///
    ///					O = Occupancy
    ///
    ///					U = Use</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Provenance Code values T = Registered land title L = Unregistered land title F = " +
        "Formal tenancy agreement R = Rental agreement P = Physical features O = Occupanc" +
        "y U = Use")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProvenanceCodeType", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum ProvenanceCodeType
    {
        
        T,
        
        L,
        
        F,
        
        R,
        
        P,
        
        O,
        
        U,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProvenanceStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProvenanceStructure
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ProvenanceCode")]
        public ProvenanceCodeType ProvenanceCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Annotation")]
        public string Annotation { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ProvEntryDate", DataType="date")]
        public System.DateTime ProvEntryDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ProvStartDate", DataType="date")]
        public System.DateTime ProvStartDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ProvEndDate", DataType="date")]
        public System.DateTime ProvEndDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ProvEndDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvEndDateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ProvLastUpdateDate", DataType="date")]
        public System.DateTime ProvLastUpdateDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BLPUextent")]
        public BlpUextentStructure BlpUextent { get; set; }
    }
    
    /// <summary>
    /// <para>Representative Point Code values
    ///
    ///					1 = Visual centre
    ///
    ///					2 = General internal point
    ///
    ///					3 = South-west corner of 100m grid square
    ///
    ///					4 = Start point of the referenced street</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Representative Point Code values 1 = Visual centre 2 = General internal point 3 =" +
        " South-west corner of 100m grid square 4 = Start point of the referenced street")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RepresentativePointCodeType", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum RepresentativePointCodeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <summary>
    /// <para>Logical Status values
    ///
    ///					1 = Approved preferred
    ///
    ///					2 = Approved alternative (LPI Only)
    ///
    ///					3 = Alternative (LPI Only)
    ///
    ///					5 = Candidate
    ///
    ///					6 = Provisional
    ///
    ///					8 = Historical
    ///
    ///					9 = Rejected</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Logical Status values 1 = Approved preferred 2 = Approved alternative (LPI Only) " +
        "3 = Alternative (LPI Only) 5 = Candidate 6 = Provisional 8 = Historical 9 = Reje" +
        "cted")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LogicalStatusType", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum LogicalStatusType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicLandAndPropertyUnitStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BS7666BLPU", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BasicLandAndPropertyUnitStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "1", "999999999999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("UniquePropertyReferenceNumber")]
        public ulong UniquePropertyReferenceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "1", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CustodianCode")]
        public ushort CustodianCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("RepresentativePointCode")]
        public RepresentativePointCodeType RepresentativePointCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalStatus")]
        public LogicalStatusType LogicalStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("GridReference")]
        public CoordinateStructure GridReference { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BLPUentryDate", DataType="date")]
        public System.DateTime BlpUentryDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BLPUstartDate", DataType="date")]
        public System.DateTime BlpUstartDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BLPUendDate", DataType="date")]
        public System.DateTime BlpUendDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BlpUendDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlpUendDateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BLPUlastUpdateDate", DataType="date")]
        public System.DateTime BlpUlastUpdateDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LandAndPropertyIdentifierStructure> _landAndPropertyIdentifier;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LandAndPropertyIdentifier")]
        public System.Collections.ObjectModel.Collection<LandAndPropertyIdentifierStructure> LandAndPropertyIdentifier
        {
            get
            {
                return _landAndPropertyIdentifier;
            }
            private set
            {
                _landAndPropertyIdentifier = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BasicLandAndPropertyUnitStructure" /> class.</para>
        /// </summary>
        public BasicLandAndPropertyUnitStructure()
        {
            this._landAndPropertyIdentifier = new System.Collections.ObjectModel.Collection<LandAndPropertyIdentifierStructure>();
            this._provenance = new System.Collections.ObjectModel.Collection<ProvenanceStructure>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProvenanceStructure> _provenance;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Provenance")]
        public System.Collections.ObjectModel.Collection<ProvenanceStructure> Provenance
        {
            get
            {
                return _provenance;
            }
            private set
            {
                _provenance = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LandAndPropertyIdentifierStructure", Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LandAndPropertyIdentifierStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Pattern: [0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PAON")]
        public string Paon { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Pattern: [0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 ]{4}[A-Z ]([0-9 ]{4}[A-Z ][0-Z%-+a-z ]{0,90})?")]
        [System.Xml.Serialization.XmlElementAttribute("SAON")]
        public string Saon { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("PostTown")]
        public string PostTown { get; set; }
        
        /// <summary>
        /// <para>complex pattern for postcode, which matches definition, accepted by some parsers is: "(GIR 0AA)|((([A-Z-[QVX]][0-9][0-9]?)|(([A-Z-[QVX]][A-Z-[IJZ]][0-9][0-9]?)|(([A-Z-[QVX]][0-9][A-HJKSTUW])|([A-Z-[QVX]][A-Z-[IJZ]][0-9][ABEHMNPRVWXY])))) [0-9][A-Z-[CIKMOV]]{2})"</para>
        /// <para xml:lang="en">Pattern: [A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("PostCode")]
        public string PostCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("Level")]
        public string Level { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalStatus")]
        public LogicalStatusType LogicalStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OfficialAddressMarker")]
        public bool OfficialAddressMarker { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OfficialAddressMarker property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OfficialAddressMarkerSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LPIstartDate", DataType="date")]
        public System.DateTime LpIstartDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LPIentryDate", DataType="date")]
        public System.DateTime LpIentryDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LPIendDate", DataType="date")]
        public System.DateTime LpIendDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the LpIendDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LpIendDateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LPIlastUpdateDate", DataType="date")]
        public System.DateTime LpIlastUpdateDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Street")]
        public StreetStructure Street { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(uint), "1", "99999999", ConvertValueInInvariantCulture=true)]
        [System.Xml.Serialization.XmlElementAttribute("USRN")]
        public uint Usrn { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Usrn property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsrnSpecified { get; set; }
    }
}
