//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf TransXChange_namespace_mapping.txt -o output --nc TransXChange_general.xsd
namespace BodsDotNet.Schemas.TransXChange.People.PersonDescriptives
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VerificationLevelType", Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public enum VerificationLevelType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Level 0")]
        Level0,
        
        [System.Xml.Serialization.XmlEnumAttribute("Level 1")]
        Level1,
        
        [System.Xml.Serialization.XmlEnumAttribute("Level 2")]
        Level2,
        
        [System.Xml.Serialization.XmlEnumAttribute("Level 3")]
        Level3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PersonBirthDateStructure", Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonBirthDateStructure
    {
        
        /// <summary>
        /// <para>A Common DataType W 3C XML Schema datetype</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PersonBirthDate", DataType="date")]
        public System.DateTime PersonBirthDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationLevel")]
        public VerificationLevelType VerificationLevel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VerificationLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PersonDeathDateStructure", Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonDeathDateStructure
    {
        
        /// <summary>
        /// <para>A Common DataType W 3C XML Schema datetype</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PersonDeathDate", DataType="date")]
        public System.DateTime PersonDeathDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationLevel")]
        public VerificationLevelType VerificationLevel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VerificationLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PersonMaritalStatusStructure", Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonMaritalStatusStructure
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MaritalStatus")]
        public BodsDotNet.Schemas.TransXChange.Core.MaritalStatusType MaritalStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationLevel")]
        public VerificationLevelType VerificationLevel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VerificationLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PersonMaritalStatus", Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonMaritalStatus
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public BodsDotNet.Schemas.TransXChange.Core.MaritalStatusType Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("VerificationLevel")]
        public VerificationLevelType VerificationLevel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VerificationLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified { get; set; }
    }
}
