//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf TransXChange_namespace_mapping.txt -o output --nc TransXChange_general.xsd
namespace BodsDotNet.Schemas.TransXChange.Empty
{
    
    
    /// <summary>
    /// <para>A type with no allowed content, used when simply the presence of an element is significant.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A type with no allowed content, used when simply the presence of an element is si" +
        "gnificant.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EmptyType", Namespace="")]
    public enum EmptyType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Empty,
    }
    
    /// <summary>
    /// <para>Type for Extensions to schema. Wraps an 'any' tag to ensure decidability.</para>
    /// <para>Extensions to schema. (Wrapper tag used to avoid problems with handling of optional 'any' by some validators).</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Type for Extensions to schema. Wraps an \'any\' tag to ensure decidability. Extensi" +
        "ons to schema. (Wrapper tag used to avoid problems with handling of optional \'an" +
        "y\' by some validators).")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionsAnyStructure", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Extensions", Namespace="")]
    public partial class ExtensionsAnyStructure
    {
        
        /// <summary>
        /// <para>Placeholder for user extensions.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Placeholder for user extensions.")]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any { get; set; }
    }
    
    /// <summary>
    /// <para>@lang. ISO language code (default is en)
    ///
    ///A string containing a phrase in a natural language.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("@lang. ISO language code (default is en) A string containing a phrase in a natura" +
        "l language.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NaturalLanguageStringStructure", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NaturalLanguageStringStructure", Namespace="")]
    public partial class NaturalLanguageStringStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("lang", Namespace="http://www.w3.org/XML/1998/namespace", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Lang { get; set; }
    }
    
    /// <summary>
    /// <para>@lang. ISO language code (default is en)
    ///
    ///A string containing a phrase in a natural language name that requires at least one character of text and forbids certain reserved characters.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("@lang. ISO language code (default is en) A string containing a phrase in a natura" +
        "l language name that requires at least one character of text and forbids certain" +
        " reserved characters.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NaturalLanguagePlaceNameStructure", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NaturalLanguagePlaceNameStructure", Namespace="")]
    public partial class NaturalLanguagePlaceNameStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 48.</para>
        /// <para xml:lang="en">Pattern: [^,\[\]\{\}\?$£%\^=@#;:]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(48)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[^,\\[\\]\\{\\}\\?$£%\\^=@#;:]+")]
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("lang", Namespace="http://www.w3.org/XML/1998/namespace", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Lang { get; set; }
    }
    
    /// <summary>
    /// <para>A telephone number, using GovTalk constructs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A telephone number, using GovTalk constructs.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TelephoneContactStructure", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TelephoneContactStructure", Namespace="")]
    public partial class TelephoneContactStructure
    {
        
        /// <summary>
        /// <para>Full telephone number including STD prefix</para>
        /// <para xml:lang="en">Pattern: [0-9 \-]{1,20}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Full telephone number including STD prefix")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 \\-]{1,20}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TelNationalNumber")]
        public string TelNationalNumber { get; set; }
        
        /// <summary>
        /// <para>Any additional extension number.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,6}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Any additional extension number.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,6}")]
        [System.Xml.Serialization.XmlElementAttribute("TelExtensionNumber")]
        public string TelExtensionNumber { get; set; }
        
        /// <summary>
        /// <para>Two character country prefix, e.g. 44 for UK.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Two character country prefix, e.g. 44 for UK.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.Xml.Serialization.XmlElementAttribute("TelCountryCode")]
        public string TelCountryCode { get; set; }
    }
    
    /// <summary>
    /// <para>Person Name required in full..</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Person Name required in full..")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FullPersonNameStructure", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("FullPersonNameStructure", Namespace="")]
    public partial class FullPersonNameStructure
    {
        
        /// <summary>
        /// <para>Position of responsibility of the person, job title. @lang.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Position of responsibility of the person, job title. @lang.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public BodsDotNet.Schemas.TransXChange.Empty.NaturalLanguageStringStructure Position { get; set; }
        
        /// <summary>
        /// <para>Title (i.e. Mr, Mrs, Miss, Ms, Rev, Rt.Hon etc).</para>
        /// <para>A restriction of W3C XML Schema's string that requires at least one character of text.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Title (i.e. Mr, Mrs, Miss, Ms, Rev, Rt.Hon etc).")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title { get; set; }
        
        /// <summary>
        /// <para>Forename of the person</para>
        /// <para>A restriction of W3C XML Schema's string that requires at least one character of text.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Forename of the person")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Forename")]
        public string Forename { get; set; }
        
        /// <summary>
        /// <para>Surname of the person.</para>
        /// <para>A restriction of W3C XML Schema's string that requires at least one character of text.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Surname of the person.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Surname")]
        public string Surname { get; set; }
    }
}
