//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf TransXChange_namespace_mapping.txt -o output --nc TransXChange_general.xsd
namespace BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InternationalAddressStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InternationalAddressStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _intAddressLine;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("IntAddressLine")]
        public System.Collections.ObjectModel.Collection<string> IntAddressLine
        {
            get
            {
                return _intAddressLine;
            }
            private set
            {
                _intAddressLine = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="InternationalAddressStructure" /> class.</para>
        /// </summary>
        public InternationalAddressStructure()
        {
            this._intAddressLine = new System.Collections.ObjectModel.Collection<string>();
            this._country = new System.Collections.ObjectModel.Collection<string>();
            this._internationalPostCode = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _country;
        
        [System.Xml.Serialization.XmlElementAttribute("Country")]
        public System.Collections.ObjectModel.Collection<string> Country
        {
            get
            {
                return _country;
            }
            private set
            {
                _country = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Country collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySpecified
        {
            get
            {
                return (this.Country.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _internationalPostCode;
        
        [System.Xml.Serialization.XmlElementAttribute("InternationalPostCode")]
        public System.Collections.ObjectModel.Collection<string> InternationalPostCode
        {
            get
            {
                return _internationalPostCode;
            }
            private set
            {
                _internationalPostCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InternationalPostCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternationalPostCodeSpecified
        {
            get
            {
                return (this.InternationalPostCode.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UKPostalAddressStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UkPostalAddressStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _line;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public System.Collections.ObjectModel.Collection<string> Line
        {
            get
            {
                return _line;
            }
            private set
            {
                _line = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UkPostalAddressStructure" /> class.</para>
        /// </summary>
        public UkPostalAddressStructure()
        {
            this._line = new System.Collections.ObjectModel.Collection<string>();
        }
        
        /// <summary>
        /// <para>complex pattern for postcode, which matches definition, accepted by some parsers is: "(GIR 0AA)|((([A-Z-[QVX]][0-9][0-9]?)|(([A-Z-[QVX]][A-Z-[IJZ]][0-9][0-9]?)|(([A-Z-[QVX]][0-9][A-HJKSTUW])|([A-Z-[QVX]][A-Z-[IJZ]][0-9][ABEHMNPRVWXY])))) [0-9][A-Z-[CIKMOV]]{2})"</para>
        /// <para xml:lang="en">Pattern: [A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("PostCode")]
        public string PostCode { get; set; }
    }
    
    /// <summary>
    /// <para>Supports BS7666 address types.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Supports BS7666 address types.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UKAddressStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UkAddressStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.Bs7666.BSaddressStructure> _bs7666Address;
        
        [System.Xml.Serialization.XmlElementAttribute("BS7666Address")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.Bs7666.BSaddressStructure> Bs7666Address
        {
            get
            {
                return _bs7666Address;
            }
            private set
            {
                _bs7666Address = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Bs7666Address collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bs7666AddressSpecified
        {
            get
            {
                return (this.Bs7666Address.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UkAddressStructure" /> class.</para>
        /// </summary>
        public UkAddressStructure()
        {
            this._bs7666Address = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.Bs7666.BSaddressStructure>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("A_5LineAddress")]
        public UkPostalAddressStructure A5LineAddress { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "1", "999999999999", ConvertValueInInvariantCulture=true)]
        [System.Xml.Serialization.XmlElementAttribute("UniquePropertyReferenceNumber")]
        public ulong UniquePropertyReferenceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UniquePropertyReferenceNumber property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UniquePropertyReferenceNumberSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{5}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{5}")]
        [System.Xml.Serialization.XmlElementAttribute("SortCode")]
        public string SortCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{8}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8}")]
        [System.Xml.Serialization.XmlElementAttribute("WalkSort")]
        public string WalkSort { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressQualifierType", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    public enum AddressQualifierType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("residential")]
        Residential,
        
        [System.Xml.Serialization.XmlEnumAttribute("correspondence")]
        Correspondence,
        
        [System.Xml.Serialization.XmlEnumAttribute("self-employed-business")]
        SelfEmployedBusiness,
        
        [System.Xml.Serialization.XmlEnumAttribute("business")]
        Business,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressValidationType", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    public enum AddressValidationType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("not-checked")]
        NotChecked,
        
        [System.Xml.Serialization.XmlEnumAttribute("PAF-check-failed")]
        PafCheckFailed,
        
        [System.Xml.Serialization.XmlEnumAttribute("NLPG-check-failed")]
        NlpgCheckFailed,
        
        [System.Xml.Serialization.XmlEnumAttribute("PAF-check-valid")]
        PafCheckValid,
        
        [System.Xml.Serialization.XmlEnumAttribute("NLPG-check-valid")]
        NlpgCheckValid,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TelephoneStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TelephoneStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9 \-]{1,20}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 \\-]{1,20}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TelNationalNumber")]
        public string TelNationalNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,6}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,6}")]
        [System.Xml.Serialization.XmlElementAttribute("TelExtensionNumber")]
        public string TelExtensionNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.Xml.Serialization.XmlElementAttribute("TelCountryCode")]
        public string TelCountryCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TelUse")]
        public BodsDotNet.Schemas.TransXChange.Core.WorkHomeType TelUse { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TelUse property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelUseSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TelMobile")]
        public BodsDotNet.Schemas.TransXChange.Core.YesNoType TelMobile { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TelMobile property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelMobileSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TelPreferred")]
        public BodsDotNet.Schemas.TransXChange.Core.YesNoType TelPreferred { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TelPreferred property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelPreferredSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FaxStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaxStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9 \-]{1,20}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9 \\-]{1,20}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("FaxNationalNumber")]
        public string FaxNationalNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,6}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,6}")]
        [System.Xml.Serialization.XmlElementAttribute("FaxExtensionNumber")]
        public string FaxExtensionNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.Xml.Serialization.XmlElementAttribute("FaxCountryCode")]
        public string FaxCountryCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FaxUse")]
        public BodsDotNet.Schemas.TransXChange.Core.WorkHomeType FaxUse { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FaxUse property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaxUseSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FaxMobile")]
        public BodsDotNet.Schemas.TransXChange.Core.YesNoType FaxMobile { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FaxMobile property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaxMobileSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FaxPreferred")]
        public BodsDotNet.Schemas.TransXChange.Core.YesNoType FaxPreferred { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FaxPreferred property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaxPreferredSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EmailStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z0-9\s~!"@#$%&'\(\)\*\+,\-\./:;<=>\?\[\\\]_\{\}\^£€]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z0-9\\s~!\"@#$%&\'\\(\\)\\*\\+,\\-\\./:;<=>\\?\\[\\\\\\]_\\{\\}\\^£€]*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EmailAddress")]
        public string EmailAddress { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("EmailUsage")]
        public BodsDotNet.Schemas.TransXChange.Core.WorkHomeType EmailUsage { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EmailUsage property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmailUsageSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("EmailPreferred")]
        public BodsDotNet.Schemas.TransXChange.Core.YesNoType EmailPreferred { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EmailPreferred property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmailPreferredSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NHSnumberStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NhSnumberStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Pattern: [0-9]{10}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{10}")]
        [System.Xml.Serialization.XmlElementAttribute("EWregNHSnumber")]
        public string EWregNhSnumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 18.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(18)]
        [System.Xml.Serialization.XmlElementAttribute("SregNHSnumber")]
        public string SregNhSnumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 18.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(18)]
        [System.Xml.Serialization.XmlElementAttribute("NIregNHSnumber")]
        public string NIregNhSnumber { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CitizenNameStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CitizenNameStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _citizenNameTitle;
        
        [System.Xml.Serialization.XmlElementAttribute("CitizenNameTitle")]
        public System.Collections.ObjectModel.Collection<string> CitizenNameTitle
        {
            get
            {
                return _citizenNameTitle;
            }
            private set
            {
                _citizenNameTitle = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CitizenNameTitle collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitizenNameTitleSpecified
        {
            get
            {
                return (this.CitizenNameTitle.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CitizenNameStructure" /> class.</para>
        /// </summary>
        public CitizenNameStructure()
        {
            this._citizenNameTitle = new System.Collections.ObjectModel.Collection<string>();
            this._citizenNameForename = new System.Collections.ObjectModel.Collection<string>();
            this._citizenNameSuffix = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _citizenNameForename;
        
        [System.Xml.Serialization.XmlElementAttribute("CitizenNameForename")]
        public System.Collections.ObjectModel.Collection<string> CitizenNameForename
        {
            get
            {
                return _citizenNameForename;
            }
            private set
            {
                _citizenNameForename = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CitizenNameForename collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitizenNameForenameSpecified
        {
            get
            {
                return (this.CitizenNameForename.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [A-Za-z0-9\s~!"@#$%&'\(\)\*\+,\-\./:;<=>\?\[\\\]_\{\}\^£€]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(35)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z0-9\\s~!\"@#$%&\'\\(\\)\\*\\+,\\-\\./:;<=>\\?\\[\\\\\\]_\\{\\}\\^£€]*")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CitizenNameSurname")]
        public string CitizenNameSurname { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _citizenNameSuffix;
        
        [System.Xml.Serialization.XmlElementAttribute("CitizenNameSuffix")]
        public System.Collections.ObjectModel.Collection<string> CitizenNameSuffix
        {
            get
            {
                return _citizenNameSuffix;
            }
            private set
            {
                _citizenNameSuffix = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CitizenNameSuffix collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitizenNameSuffixSpecified
        {
            get
            {
                return (this.CitizenNameSuffix.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 70.</para>
        /// <para xml:lang="en">Pattern: [A-Za-z0-9\s~!"@#$%&'\(\)\*\+,\-\./:;<=>\?\[\\\]_\{\}\^£€]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(70)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z0-9\\s~!\"@#$%&\'\\(\\)\\*\\+,\\-\\./:;<=>\\?\\[\\\\\\]_\\{\\}\\^£€]*")]
        [System.Xml.Serialization.XmlElementAttribute("CitizenNameRequestedName")]
        public string CitizenNameRequestedName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CitizenRegistrationStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CitizenRegistrationStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-CEGHJ-NOPR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[ABCD\s]{1}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-CEGHJ-NOPR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[ABCD\\s]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("NationalInsuranceNumber")]
        public string NationalInsuranceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{10}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{10}")]
        [System.Xml.Serialization.XmlElementAttribute("UniqueTaxReference")]
        public string UniqueTaxReference { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Pattern: [A-Z,0-9]{5}[0-9][0,1,5,6][0-9]([0][1-9]|[1-2][0-9]|[3][0,1])[0-9][A-Z,0-9]{3}[A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z,0-9]{5}[0-9][0,1,5,6][0-9]([0][1-9]|[1-2][0-9]|[3][0,1])[0-9][A-Z,0-9]{3}[A-" +
            "Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("DriverNumber")]
        public string DriverNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NHSNumber")]
        public BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.NhSnumberStructure NhsNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Pattern: [A-Z,0-9]{1}[0-9]{4}[A-Z,0-9]{1}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z,0-9]{1}[0-9]{4}[A-Z,0-9]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("PassportNumber_Old")]
        public string PassportNumberOld { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{9}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{9}")]
        [System.Xml.Serialization.XmlElementAttribute("PassportNumber_New")]
        public int PassportNumberNew { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PassportNumberNew property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PassportNumberNewSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{2,3}[0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{2,3}[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("ElectoralRollNumber")]
        public string ElectoralRollNumber { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CitizenDetailsStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CitizenDetailsStructure
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CitizenName")]
        public CitizenNameStructure CitizenName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CitizenRegistration")]
        public CitizenRegistrationStructure CitizenRegistration { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.Core.LanguageType> _preferredLanguages;
        
        [System.Xml.Serialization.XmlElementAttribute("PreferredLanguages")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.Core.LanguageType> PreferredLanguages
        {
            get
            {
                return _preferredLanguages;
            }
            private set
            {
                _preferredLanguages = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PreferredLanguages collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredLanguagesSpecified
        {
            get
            {
                return (this.PreferredLanguages.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CitizenDetailsStructure" /> class.</para>
        /// </summary>
        public CitizenDetailsStructure()
        {
            this._preferredLanguages = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.Core.LanguageType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ContactDetails")]
        public CitizenContactDetailsStructure ContactDetails { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: 9.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("9")]
        [System.Xml.Serialization.XmlElementAttribute("CitizenSex")]
        public sbyte CitizenSex { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CitizenSex property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitizenSexSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CitizenMaritalStatus")]
        public BodsDotNet.Schemas.TransXChange.Core.MaritalStatusType CitizenMaritalStatus { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CitizenMaritalStatus property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitizenMaritalStatusSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CitizenBirthDate")]
        public CitizenBirthDateStructure CitizenBirthDate { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CitizenContactDetailsStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CitizenContactDetailsStructure
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.EmailStructure> _email;
        
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.EmailStructure> Email
        {
            get
            {
                return _email;
            }
            private set
            {
                _email = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Email collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmailSpecified
        {
            get
            {
                return (this.Email.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CitizenContactDetailsStructure" /> class.</para>
        /// </summary>
        public CitizenContactDetailsStructure()
        {
            this._email = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.EmailStructure>();
            this._telephone = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.TelephoneStructure>();
            this._fax = new System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.FaxStructure>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.TelephoneStructure> _telephone;
        
        [System.Xml.Serialization.XmlElementAttribute("Telephone")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.TelephoneStructure> Telephone
        {
            get
            {
                return _telephone;
            }
            private set
            {
                _telephone = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Telephone collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelephoneSpecified
        {
            get
            {
                return (this.Telephone.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.FaxStructure> _fax;
        
        [System.Xml.Serialization.XmlElementAttribute("Fax")]
        public System.Collections.ObjectModel.Collection<BodsDotNet.Schemas.TransXChange.People.AddressAndPersonalDetails.FaxStructure> Fax
        {
            get
            {
                return _fax;
            }
            private set
            {
                _fax = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Fax collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaxSpecified
        {
            get
            {
                return (this.Fax.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CitizenBirthDateStructure", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CitizenBirthDateStructure
    {
        
        /// <summary>
        /// <para>A Common DataType W 3C XML Schema datetype</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BirthDate", DataType="date")]
        public System.DateTime BirthDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("VerifiedBy")]
        public VerifiedByType VerifiedBy { get; set; }
    }
    
    /// <summary>
    /// <para>A Change of Address specific data type</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A Change of Address specific data type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VerifiedByType", Namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails")]
    public enum VerifiedByType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("not verified")]
        NotVerified,
        
        [System.Xml.Serialization.XmlEnumAttribute("accepted on balance of probabilities")]
        AcceptedOnBalanceOfProbabilities,
        
        [System.Xml.Serialization.XmlEnumAttribute("secondary certificate")]
        SecondaryCertificate,
        
        [System.Xml.Serialization.XmlEnumAttribute("certified copy of birth certificate")]
        CertifiedCopyOfBirthCertificate,
        
        [System.Xml.Serialization.XmlEnumAttribute("short form birth certificate or certificate of registration of birth")]
        ShortFormBirthCertificateOrCertificateOfRegistrationOfBirth,
        
        [System.Xml.Serialization.XmlEnumAttribute("birth certificate")]
        BirthCertificate,
    }
}
