//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --nf TransXChange_namespace_mapping.txt -o output --nc TransXChange_general.xsd
namespace BodsDotNet.Schemas.TransXChange.Core
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("YesNoType", Namespace="http://www.govtalk.gov.uk/core")]
    public enum YesNoType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("yes")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("no")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MaritalStatusType", Namespace="http://www.govtalk.gov.uk/core")]
    public enum MaritalStatusType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("s")]
        S,
        
        [System.Xml.Serialization.XmlEnumAttribute("m")]
        M,
        
        [System.Xml.Serialization.XmlEnumAttribute("d")]
        D,
        
        [System.Xml.Serialization.XmlEnumAttribute("w")]
        W,
        
        [System.Xml.Serialization.XmlEnumAttribute("n")]
        N,
        
        [System.Xml.Serialization.XmlEnumAttribute("p")]
        P,
    }
    
    /// <summary>
    /// <para>A Common DataType Values from the ISO standard for 2 character language codes (ISO 639:1988 Code for the representation of names of languages).</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A Common DataType Values from the ISO standard for 2 character language codes (IS" +
        "O 639:1988 Code for the representation of names of languages).")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LanguageType", Namespace="http://www.govtalk.gov.uk/core")]
    public enum LanguageType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("en")]
        En,
        
        [System.Xml.Serialization.XmlEnumAttribute("cy")]
        Cy,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("WorkHomeType", Namespace="http://www.govtalk.gov.uk/core")]
    public enum WorkHomeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("work")]
        Work,
        
        [System.Xml.Serialization.XmlEnumAttribute("home")]
        Home,
    }
}
